---
abstract: 'Pluggable STF Dispatcher Interface'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  HTTP::Request::Common: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: STF-Dispatcher-PSGI
no_index:
  directory:
    - inc
    - t
recommends:
  Net::STF::Client: 0
requires:
  Class::Accessor::Lite: 0
  HTTP::Date: 0
  Plack: 0
  Plack::Middleware::Header: 0
  Plack::Request: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/stf-storage/stf-dispatcher-psgi.git
version: 1.07
