---
abstract: 'Pluggable STF Dispatcher Interface'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  HTTP::Request::Common: 0
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: STF-Dispatcher-PSGI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  STF::Dispatcher::Impl::File:
    file: lib/STF/Dispatcher/Impl/File.pm
    version: 0
  STF::Dispatcher::Impl::Hash:
    file: lib/STF/Dispatcher/Impl/Hash.pm
    version: 0
  STF::Dispatcher::PSGI:
    file: lib/STF/Dispatcher/PSGI.pm
    version: 1.11
  STF::Dispatcher::PSGI::HTTPException:
    file: lib/STF/Dispatcher/PSGI/HTTPException.pm
    version: 0
  STF::Dispatcher::Test:
    file: lib/STF/Dispatcher/Test.pm
    version: 0
recommends:
  Net::STF::Client: 0
requires:
  Class::Accessor::Lite: 0
  HTTP::Date: 0
  Plack: 0
  Plack::Middleware::Header: 0
  Plack::Request: 0
  Scalar::Util: 0
resources:
  bugtracker: https://github.com/stf-storage/stf-dispatcher-psgi/issues
  homepage: https://github.com/stf-storage/stf-dispatcher-psgi
  repository: git://github.com/stf-storage/stf-dispatcher-psgi.git
version: 1.11
x_contributors:
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
